# Generated by Django 4.1.2 on 2022-11-29 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 18, 46, 13, 754040)),
        ),
        migrations.AddField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 18, 46, 13, 754040)),
        ),
    ]
