# Generated by Django 4.1.2 on 2022-11-29 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_fundador_created_fundador_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 18, 49, 58, 295695)),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 18, 49, 58, 295695)),
        ),
    ]
