# Generated by Django 4.1.2 on 2022-12-05 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_alter_fundador_created_alter_fundador_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 27, 9, 452659)),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 27, 9, 452659)),
        ),
    ]
