# Generated by Django 3.0.1 on 2022-12-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_alter_fundador_created_alter_fundador_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 38, 23, 179918)),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 38, 23, 179954)),
        ),
    ]
