# Generated by Django 3.0.1 on 2022-12-06 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0010_auto_20221206_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 16, 3, 13, 241714)),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 16, 3, 13, 241744)),
        ),
    ]
